export default [
  {
    pageId: "recordHistoryManagement",
    uiActionType: "ui",
    uiActionId: "refreshTableData",
    desc: "✅获取表格数据",
    uiActionConfig: {
      before: [{ function: "openTableLoading" }],
      main: [{ function: "refreshTableData" }, { function: "computeHeader" }],
      after: [{ function: "closeTableLoading" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "recordHistoryManagement",
    uiActionType: "ui",
    uiActionId: "viewRecordHistory",
    desc: "✅版本历史列表",
    uiActionConfig: { main: [{ function: "doViewRecordHistory" }] },
    appDataSchema: "",
  },
  {
    pageId: "recordHistoryManagement",
    uiActionType: "ui",
    uiActionId: "restoreRecordByRecordHistory",
    desc: "✅数据还原",
    uiActionConfig: {
      main: [{ function: "doRestoreRecordByRecordHistory" }, { function: "doViewRecordHistory" }, { function: "refreshTableData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "refreshTableData",
    desc: "✅获取表格数据",
    uiActionConfig: {
      main: [{ function: "refreshTableData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "startCreateItem",
    desc: "✅打开创建数据抽屉",
    uiActionConfig: {
      main: [{ function: "clearItemData" }, { function: "openCreateItemDialog" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "createItem",
    desc: "✅创建数据",
    uiActionConfig: {
      before: [{ function: "prepareValidate" }, { function: "confirmCreateItemDialog" }],
      main: [{ function: "doCreateItem" }, { function: "refreshTableData" }],
      after: [{ function: "closeDrawerShow" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "startUpdateItem",
    desc: "✅打开更新数据抽屉",
    uiActionConfig: {
      main: [{ function: "prepareItemData" }, { function: "openUpdateItemDialog" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "updateItem",
    desc: "✅更新数据",
    uiActionConfig: {
      before: [{ function: "prepareValidate" }, { function: "confirmUpdateItemDialog" }],
      main: [{ function: "doUpdateItem" }, { function: "refreshTableData" }],
      after: [{ function: "closeDrawerShow" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "activeUserStatus",
    desc: "✅激活用户",
    uiActionConfig: {
      before: [{ function: "confirmActiveUserStatusDialog" }],
      main: [{ function: "prepareItemData" }, { function: "doActiveUserStatus" }, { function: "refreshTableData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "startResetPassword",
    desc: "✅打开重置密码抽屉",
    uiActionConfig: { main: [{ function: "prepareItemData" }, { function: "openResetPasswordDialog" }] },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "resetPassword",
    desc: "✅更新数据",
    uiActionConfig: {
      before: [{ function: "confirmResetPasswordDialog" }],
      main: [{ function: "doResetUserPassword" }, { function: "refreshTableData" }],
      after: [{ function: "closeDrawerShow" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userManagement",
    uiActionType: "ui",
    uiActionId: "bannedUserStatus",
    desc: "✅禁用用户",
    uiActionConfig: {
      before: [{ function: "confirmBannedUserStatusDialog" }],
      main: [{ function: "prepareItemData" }, { function: "doBannedUserStatus" }, { function: "refreshTableData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "refreshTableData",
    desc: "✅获取表格数据",
    uiActionConfig: { main: [{ function: "refreshTableData" }] },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "startCreateItem",
    desc: "✅打开创建数据抽屉",
    uiActionConfig: { main: [{ function: "clearItemData" }, { function: "openCreateItemDialog" }] },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "createItem",
    desc: "✅创建数据",
    uiActionConfig: {
      before: [{ function: "confirmCreateItemDialog" }],
      main: [{ function: "doCreateItem" }, { function: "refreshTableData" }],
      after: [{ function: "closeDrawerShow" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "startUpdateItem",
    desc: "✅打开更新数据抽屉",
    uiActionConfig: {
      main: [{ function: "prepareItemData" }, { function: "openUpdateItemDialog" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "updateItem",
    desc: "✅更新数据",
    uiActionConfig: {
      before: [{ function: "confirmUpdateItemDialog" }],
      main: [{ function: "doUpdateItem" }, { function: "refreshTableData" }],
      after: [{ function: "closeDrawerShow" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "deleteItem",
    desc: "✅删除数据",
    uiActionConfig: {
      before: [{ function: "confirmDeleteItemDialog" }],
      main: [{ function: "prepareItemData" }, { function: "doDeleteItem" }, { function: "refreshTableData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "startCreateLeftItem",
    desc: "✅打开创建数据抽屉",
    uiActionConfig: {
      main: [{ function: "openFormDialog" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "createLeftItem",
    desc: "✅创建数据",
    uiActionConfig: {
      main: [{ function: "addNewItem" }, { function: "reGetLeftData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "updateLeftItem",
    desc: "✅更新数据",
    uiActionConfig: {
      main: [{ function: "updateLeftItem" }, { function: "reGetLeftData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "deleteLeftItem",
    desc: "✅删除数据",
    uiActionConfig: {
      main: [{ function: "deleteLeftItem" }, { function: "reGetLeftData" }],
    },
    appDataSchema: "",
  },
  {
    pageId: "userGroupRoleManagement",
    uiActionType: "ui",
    uiActionId: "initOptions",
    desc: "✅获取表格数据",
    uiActionConfig: {
      main: [{ function: "selectUser" }, { function: "refreshTableData" }, { function: "initOptions" }],
    },
    appDataSchema: "",
  },
];
